// Generated by gencpp from file lab2_pkg/rawTwist.msg
// DO NOT EDIT!


#ifndef LAB2_PKG_MESSAGE_RAWTWIST_H
#define LAB2_PKG_MESSAGE_RAWTWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lab2_pkg/Vector3.h>
#include <lab2_pkg/Vector3.h>

namespace lab2_pkg
{
template <class ContainerAllocator>
struct rawTwist_
{
  typedef rawTwist_<ContainerAllocator> Type;

  rawTwist_()
    : linear()
    , angular()  {
    }
  rawTwist_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::lab2_pkg::Vector3_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::lab2_pkg::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::lab2_pkg::rawTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2_pkg::rawTwist_<ContainerAllocator> const> ConstPtr;

}; // struct rawTwist_

typedef ::lab2_pkg::rawTwist_<std::allocator<void> > rawTwist;

typedef boost::shared_ptr< ::lab2_pkg::rawTwist > rawTwistPtr;
typedef boost::shared_ptr< ::lab2_pkg::rawTwist const> rawTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2_pkg::rawTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2_pkg::rawTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab2_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lab2_pkg': ['/home/skysar/Documents/spring18/EE5531/lab2/jackal_jammers/workspace/src/lab2_pkg/msg', '/home/skysar/Documents/spring18/EE5531/lab2/jackal_jammers/workspace/src/lab2_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab2_pkg::rawTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2_pkg::rawTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_pkg::rawTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_pkg::rawTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_pkg::rawTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_pkg::rawTwist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2_pkg::rawTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f195f881246fdfa2798d1d3eebca84a";
  }

  static const char* value(const ::lab2_pkg::rawTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f195f881246fdfaULL;
  static const uint64_t static_value2 = 0x2798d1d3eebca84aULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2_pkg::rawTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2_pkg/rawTwist";
  }

  static const char* value(const ::lab2_pkg::rawTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2_pkg::rawTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3 linear \n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: lab2_pkg/Vector3\n\
#this can be used now to create vector messages\n\
#rawTwist.msg uses this file. Refer to it as example\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::lab2_pkg::rawTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2_pkg::rawTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rawTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2_pkg::rawTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2_pkg::rawTwist_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::lab2_pkg::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::lab2_pkg::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_PKG_MESSAGE_RAWTWIST_H
